### PR TITLE
fix: support commits with no scope

### PR DESCRIPTION
**Pull request by mrfelton**
Fix for #3

### CODE REVIEW

**Comment by turbobeast** [comment]
is `scope` optional?

**Comment by mrfelton** [comment]
As I understand it, yes. https://github.com/kentcdodds/validate-commit-msg doesn't require one, and neither does https://github.com/commitizen/cz-cli

**Comment by turbobeast** [comment]
okay, write a unit test for this (should be very easy), and we'll see if @jeffheifetz will merge it.

**Comment by jeffheifetz** [comment]
You make me sound like an ogre, I was about to ask for the same thing

**Comment by turbobeast** [comment]
Did I make it sound like an offering of unit tests is required to placate you? This was not my intention.... but it's probably accurate. 👹

**Comment by jeffheifetz** [comment]
@mrfelton Are you willing to update the unit tests to cover the no scope scenarios?

**Comment by mrfelton** [comment]
Sure, have update the PR @jeffheifetz to include an additional test case to cover commit messages with no scope.

**Comment by jeffheifetz** [comment]
Hi @mrfelton I don't want to seem to picky here, so I understand if this sounds too much. But I'd feel more comfortable with tests that showed that the new functionality resulted in something happening rather than a simple null. Something like the following would suffice, although one the covered the custom case couldn't hurt either. 

```
test('findMostRelevantUpdate - docs -- no scope', (t) => {
  const fakeCommits = [
    {
      message: 'some poorly formatted commit message'
    }, {
      message: 'docs: something changed'
    }, {
      message: 'Merge Commit -- bad commit message'
    }]

  t.is(findMostRelevantUpdate(fakeCommits), 'patch')
})

```

**Comment by mrfelton** [comment]
Sorry, my bad. I guess I knocked it together too quickly for my own good. Have updated the PR.

> although one the covered the custom case couldn't hurt either.

I assume you are referring to custom scopes here? Given that this change is testing commits without any scope, it doesn't seem relevant.

**Review by turbobeast — APPROVED** [review]
👍

**Pull request merged**
